version: "3.9"

name: article-service
services:
  db:
    image: postgres:16.2-alpine3.19
    environment:
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-strongpassword}
      - POSTGRES_DB=${DB_NAME:-article-newsletter}
    ports:
      - "${DB_PORT:-6500}:5432"
    volumes:
      - article_service_postgres_data:/var/lib/postgresql/data
    env_file:
      - ../.env

  api:
    image: article-service:latest
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    ports:
      - "${PORT:-8082}:8080"
    depends_on:
      - db
    env_file:
      - ../.env

volumes:
  article_service_postgres_data: